### ISSUE TITLE
Sonos Zone API has changed (since update)

### ISSUE THREAD

**Issue by CajunDust** [sonos-web/sonos-web#10]
Hello,
I posted the same issue on the unofficial sonos-app and the noson-app. Apparently sonos has changed it's API, and has done something with the zones discovery....

When I start the application, I get the error:

`An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'ZoneGroup' of undefined\n at GetZoneGroupState.then (/home/pedl/.sonos-web/node_modules/sonos/lib/services/ZoneGroupTopology.js:46:76)\n at processTicksAndRejections (internal/process/next_tick.js:81:5)","message":"Cannot read property 'ZoneGroup' of undefined"}`

Currently using the firmware version 10.2 (build 50163230)  on both my Sonos One and Beam

**Comment by Villarrealized** [comment]
Hi, I will take a look at this soon. It does seem that the API has changed. I will work on a fix when I can. I’m currently out of town until Tuesday.

**Comment by dzove855** [comment]
@Villarrealized I have checked and the xml has change.

sonos/lib services/ZoneGroupTopology.js:46 : 
let groups = (await Helpers.ParseXml(state.ZoneGroupState)).ZoneGroups.ZoneGroup

should be:
let groups = (await Helpers.ParseXml(state.ZoneGroupState)).ZoneGroupState.ZoneGroups.ZoneGroup

**Comment by Villarrealized** [comment]
Hi, thank you @dzove855. I still haven't had a chance to get into this. Would you like to make a pull request with this change?

**Comment by Villarrealized** [comment]
Actually, it appears that node-sonos has been updated and this issue has been fixed in the library. I should be able to fix this issue this weekend.

**Comment by dzove855** [comment]
I didn't have seen that it was updated. 

I think you should use the main git as depend instead of : it+https://github.com/Villarrealized/node-sonos.git#feature/add-soundcloud-support

It would be much easyer to push on the main repo instead of mergin in your repo and on a different branch

**Comment by Villarrealized** [comment]
Yeah, I will update to the main repo now. It had to be that way for a while because there were changed I made that had not been accepted as a pull request to the repo. But now everything has been merged so I can use the main repo now.

**Comment by dzove855** [comment]
okei nice, it will be much easyer like this. Thanks for the fix.

**Comment by DKHNS** [comment]
So it is possible to sonos-web update now? I have just tried but it does not seem to work :-(

**Comment by dzove855** [comment]
@DKHNS it's still not pushed, i think @Villarrealized will do it when he will be back.

**Comment by DKHNS** [comment]
Fine - no problems :-)  I am a novice re Linux, so I really don't know how to interpret your discussions :-)

I will try for update in a few days again :-)

**Comment by Villarrealized** [comment]
This issue has been fixed in v0.9.4
