### ISSUE TITLE
Error - ZoneGroup

### ISSUE THREAD

**Issue by DKHNS** [sonos-web/sonos-web#11]
Sonos-web seems awesome - according to the screen shots.

However, it will not start. 

I've installed it on my Ubuntu-installation on my QNAP server. Everything seems to go well through the installation, but the following error occurs when starting. It does start the web page by searching for the sonos installation, so the engine starts. However, after 10 seconds the error displays:

An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'ZoneGroup' of undefined\n at GetZoneGroupState.then (/home/hns/.sonos-web/node_modules/sonos/lib/services/ZoneGroupTopology.js:46:76)\n at processTicksAndRejections (internal/process/task_queues.js:86:5)","message":"Cannot read property 'ZoneGroup' of undefined"}

What to do?

Kind regards,
Henrik.

**Comment by Villarrealized** [comment]
Hi Henrik,

It seems that the underlying API has changed and is causing errors. I will work on a fix as soon as I can. I’m out of town right now but will take a look by the middle of next week.

Thanks!

**Comment by DKHNS** [comment]
Thanks a lot - I hope that this interface will help me to use my Ipad2 even when the Sonos app has outdated the ipad2 :-)

I think Home Assistant is affected as well by the change in the sonos api.

**Comment by DKHNS** [comment]
....and speakerscenes.com as well :-)

**Comment by Villarrealized** [comment]
You’re welcome!  I have tested it on an iPad and it seems to work well from what I remember :)

**Comment by DKHNS** [comment]
Thanks again - i must admit that I'm quite unfamiliar with Linux, so it was a bit of an experiment, just before I throw the iPad2 in the trash....:-)

When the update arrives - should I just type "sonos-web update" in the SSH command-line, or how will this work?

**Comment by Villarrealized** [comment]
Yep that’s right. `sonos-web update` will take care of the update for you when the time comes.

**Comment by Villarrealized** [comment]
This issue has been fixed in v0.9.4
