### ISSUE TITLE
All Music Sources Not Showing

### ISSUE THREAD

**Issue by raider-com** [sonos-web/sonos-web#126]
I'm not sure if I'm doing something wrong or not, but when I start the app, I cannot see all of the music sources listed, as I can in the official sonos android app.  The best I can get is if I start music playing on the Sonos speakers from the Android app, I can control those sessions from sonos-web.

Specifically, I can't see the bonob music service that is registered with my Sonos speakers.  This service works fine from the sonos android app.

Just running into issues playing music without having and unlocking my phone all the time.

Please let me know if I can clarify, or provide information.

**Comment by stufisher** [comment]
The only supported music services are internal music library, spotify, and soundcloud (partially). Other things you can access if they are added as sonos favourites.
