### ISSUE TITLE
Install problem on ubuntu18.04

### ISSUE THREAD

**Issue by tpso1965** [sonos-web/sonos-web#17]
Tryed to install on new ubuntu 18.04 installation. It failed during compile cli. No messages in the log, that indicated what was wrong. The current default node version on 18.04 is v8. I upgraded
node to v10, by adding de official node 10 reposity, and after the sonos-web installed correctly.

**Comment by Villarrealized** [comment]
Thank you. I will add this to the Readme that node v10 is a minimum requirement.
