### ISSUE TITLE
Radio channels

### ISSUE THREAD

**Issue by tpso1965** [sonos-web/sonos-web#18]
Is it posible to get access to start radio-playing via TuneIn from sonos-web ?

**Comment by gurtfrobe** [comment]
+1 for this

**Comment by Villarrealized** [comment]
I will look into adding this soon. I'm working on fixing a couple other bugs and updating some of the dependencies, but will look into this after that.

**Comment by stufisher** [comment]
If you add them to "my sonos", then you can browse them. from my sonos > favourites
