### ISSUE TITLE
Libary and Search not working

### ISSUE THREAD

**Issue by thilojaeggi** [sonos-web/sonos-web#2]
Hey its me again
When I go to Library or Search nothing shows up. No search bar etc.
Is that normal behavior?
Thank you.

**Comment by Villarrealized** [comment]
Yes, I am in the process of adding the music library and search functions. Hopefully within the next week or so. 🙂

**Comment by Villarrealized** [comment]
Library is now working! Search is coming later.

**Comment by Villarrealized** [comment]
Search is now working! https://github.com/Villarrealized/sonos-web/releases/tag/v0.6.0
