### ISSUE TITLE
Question: Managing devices

### ISSUE THREAD

**Issue by ghost** [sonos-web/sonos-web#20]
Do you think it would be possible to have a way of restricting/managing which devices can be controlled from the webinterface?

**Comment by Villarrealized** [comment]
Hi, this is possible, but not within the scope of the current project. It would require adding a database w/ logins, accounts, etc. There are some other more basic features and bugs that I will be focusing on first, but it's possible I could come back to the idea of having a database with other features including this one.

**Comment by Villarrealized** [comment]
Closing this issue for now. May revisit later.
