### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by gieljnssns** [sonos-web/sonos-web#3]
Why did you remove docker support?

**Comment by Villarrealized** [comment]
I love Docker, but unfortunately it would only work on Linux because of the need to use `network_mode: 'host'` for discovering the Sonos network. It seems that, at least for now, only Linux machines have proper support at this point for that feature. I wanted a cross-platform way of installing sonos-web, and so because of this issue, docker support was dropped.

https://docs.docker.com/network/network-tutorial-host/#prerequisites
Check out these issues for more information: 
https://github.com/docker/for-mac/issues/1031
https://github.com/docker/for-win/issues/937

**Comment by pwt** [comment]
I'm creating a containerised version of sonos-web for Raspberry Pis. Do you happen to know what the correct CMD statement in the Dockerfile needs to be? The command:
```CMD sonos-web start```
succeeds, but then the container immediately exits.

**Comment by Villarrealized** [comment]
@pwt 

When you run `sonos-web install` it sticks the installation under ~/.sonos-web. `sonos-web start` uses forever to start the application. For the Dockerfile, I would skip using `sonos-web start` and run `node src/server.js` from the ~/.sonos-web directory.

And you'll need to mount the .env file that's in there too.

**Comment by pwt** [comment]
Great -- that works (because it doesn't exit like `sonos-web start`). Thanks!

**Comment by gieljnssns** [comment]
The reason I'm asking this is, I'm using [Home-assistant](https://www.home-assistant.io).
Especially [Hass.io](https://www.home-assistant.io/hassio/), this is basically a dockerised version of home-assistant. People can develop [add-ons](https://developers.home-assistant.io/docs/en/hassio_addon_index.html) (other docker containers) so you can easily install other things on your machine.
And I hope some-one will make an add-on for Sonos-web...

**Comment by Villarrealized** [comment]
Very cool. Maybe you can give it a shot? I don't have the time for it right now, but I welcome the effort!

**Comment by pwt** [comment]
I've created a Docker image of sonos-web for later Raspberry Pi (ARMv7) systems. Basic instructions are at https://github.com/pwt/docker-sonos-web-arm. It's been gently tested and appears to work.

I'll aim to flesh this out and keep it up to date as **sonos-web** evolves.

**Comment by Villarrealized** [comment]
Great, thank you! I'll be sure to add it to the README soon.

**Comment by Villarrealized** [comment]
@pwt Just pulled the image and it works great on my Raspberry Pi. Thanks!

Would you mind adding version tags synonymous with the versions here so that people know which version of sonos-web they are pulling?

I will update the README with this.

**Comment by pwt** [comment]
Good.

I'll look at tagging. The images are built automatically by Docker Hub triggering off changes to my Github repo, so there is some machinery required.

**Comment by gieljnssns** [comment]
> The reason I'm asking this is, I'm using [Home-assistant](https://www.home-assistant.io).
> Especially [Hass.io](https://www.home-assistant.io/hassio/), this is basically a dockerised version of home-assistant. People can develop [add-ons](https://developers.home-assistant.io/docs/en/hassio_addon_index.html) (other docker containers) so you can easily install other things on your machine.
> And I hope some-one will make an add-on for Sonos-web...

When I have a lot of time, I will try to make an add-on, I don't have experience with this...
For now I've installed Sonos-web on a spare raspberry pi.
So closing this issue
