### ISSUE TITLE
Group volume control not working

### ISSUE THREAD

**Issue by carbonized** [sonos-web/sonos-web#30]
Group volume control doesn't seem to be working correctly. It's often pegged at "0" on the main group volume slider and cannot be changed; if clicking to show each speaker within the group it's intermittently possible to change the volume of independent speakers but the behavior is sporadic and volume level is jumpy.

**Comment by khwsjameso** [comment]
Hi, I found the same thing with group controls.  

+1

**Comment by MLDMoritz** [comment]
Also expecting this, making the thing unusable.

**Comment by stufisher** [comment]
Fixed in https://github.com/sonos-web/sonos-web/commit/2e382c33dca122fed9ba51cfd572262a6f1493eb
