### ISSUE TITLE
Can't install 0.9.9

### ISSUE THREAD

**Issue by Gryffon-G-Wiz** [sonos-web/sonos-web#33]
Hi,

I have just gone to install my first install of Sonos-Web, and found that the install fails during the install front-end dependencies. I'm advised to look at the log but the log is blank. I can see that less then a month ago this issue was reported for an older version. Not sure if the issue was resolved in this version and this is anther new issue or not, so before I tried the steps listed there I though I should submit a new issue.

![Capture 1](https://user-images.githubusercontent.com/60376863/73236224-ae8cca00-41e5-11ea-8d2d-c145c53b9b72.PNG)

Cheers,
Jake.

**Comment by robertfraefel** [comment]
Same problem here. and the log file blank. Can somebody help?

**Comment by stufisher** [comment]
See https://github.com/sonos-web/sonos-web/issues/88
