### ISSUE TITLE
Sonos speakers are muted

### ISSUE THREAD

**Issue by dehgeh** [sonos-web/sonos-web#35]
As soon as Sonos web is started some speakers are muted and can't be unmuted while increasing their volume. Im running it on a raspberry pi 3 stretch Debian with the newest version.

**Comment by carbonized** [comment]
Also having this issue and reported it here, though perhaps not as clear w.r.t. the mute issue that your post is describing: https://github.com/Villarrealized/sonos-web/issues/30

Are you only seeing this on Grouped zones, or also on individual speakers ?

**Comment by stufisher** [comment]
Fixed in https://github.com/sonos-web/sonos-web/commit/2e382c33dca122fed9ba51cfd572262a6f1493eb
