### ISSUE TITLE
Support for TuneIn or Spotify?

### ISSUE THREAD

**Issue by thilojaeggi** [sonos-web/sonos-web#5]
Just wanted to ask if that is planned or if it is possible? Thank You for adding the Search and Library function btw.

**Comment by cschnider** [comment]
I‘m also interested in these two sources.

**Comment by Villarrealized** [comment]
Yes, integrating other music services will be in the next planned release. Hopefully that will be soon. Will just depend on the difficulty of integration. Spotify will be first to be included with other services being added as I can.

**Comment by vMarkus** [comment]
would be great to consider [Subsonic](http://www.subsonic.org) as valid source as well

**Comment by Villarrealized** [comment]
Initial Spotify support is now available in [v0.9.0](https://github.com/Villarrealized/sonos-web/releases/tag/v0.9.0)! Will add search ability later. Make sure to use v0.9.2 and _not_ v0.9.0 or v0.9.1 as there are massive layout issues in both of those releases.

**Comment by cschnider** [comment]
Thank you. I updated to version v.0.9.2. Unfortunately if I click on „Connect Spotify Account“ nothing happens and just a blank screen appears.
![7fb7143f-d130-437a-91c0-88b7d8bdcf91](https://user-images.githubusercontent.com/7898408/53225388-28ccda00-3678-11e9-9d89-7cc683863446.jpeg)
![69312075-4118-4c8c-87c4-40ac863aea6b](https://user-images.githubusercontent.com/7898408/53225403-34200580-3678-11e9-8c18-164e54025251.jpeg)

**Comment by Villarrealized** [comment]
@cschnider 

Thank you for catching this. I have solved the issue in v0.9.3. There is a limitation to the Spotify authorization, however. You must authorize Spotify from the machine that the Sonos Web server is running on. For example, you must authorize Spotify from localhost:5050 and not say, 192.168.0.16:5050. The reason for this is that the Spotify API requires the redirect URL be defined in the Developer Dashboard and since I cannot add a wildcard route, the only allowable redirect URL is localhost:5050.

Once Spotify is authorized from the machine the Sonos Web server is running on, you may then access Spotify from a different machine and use it without issue.

**Comment by cschnider** [comment]
Thank you. I'm running Sonos Web on a headless machine.. so this won't work, right?

**Comment by Villarrealized** [comment]
~~Right, you won’t be able to connect Spotify on the headless machine. However, the easiest way to get it to work is to install Sonos Web on a desktop/laptop and then authorize Spotify in your web browser. Once authorized, the tokens are cached in the browser, so you will be able to use Spotify on Sonos Web from your headlesss machine after that.~~

@cschnider 
You won’t be able to connect Spotify on the headless machine due the lack of being able to access a web browser and authorize. However, the easiest way to get it to work (for now) is to install Sonos Web on a desktop/laptop and then authorize Spotify in your web browser. Once authorized, the tokens are cached in the browser. You must then copy the `localStorage` spotify settings to the browser where your headless install is running. After that you will be able to use Spotify on Sonos Web from your headlesss machine.

```javascript
// Open up developer tools console on localhost:5050
// Authorize Spotify, and then proceed with below:
var settings = JSON.parse(localStorage.settings)
settings.spotify
// copy the output of the above command to you clipboard
// should look something like this
{refreshToken: "yourLongStreamOfCharactersRefreshTokenIdHere"}

// Open up developer tools on your remote/headless machine ex. 192.168.0.200:5050
// run the following code in the console
var settings = JSON.parse(localStorage.settings)
// paste what you copied earlier from your clipboard to after the equals sign
settings.spotify = {refreshToken: "yourLongStreamOfCharactersRefreshTokenIdHere"}
localStorage.setItem('settings', JSON.stringify(settings))
```

After this, accessing Spotify on your headless machine should work properly.
