### ISSUE TITLE
when start server 

### ISSUE THREAD

**Issue by omarlachhab** [sonos-web/sonos-web#53]
![Capture](https://user-images.githubusercontent.com/30928791/91290655-ca604a80-e78b-11ea-82ba-c7740baacb22.PNG)

**Comment by jamestalmage** [comment]
I am also having this issue.

**Comment by jat255** [comment]
:+1:  seeing this too using Node v14.12.0 and npm v6.14.8 on a Debian 10 server

**Comment by jat255** [comment]
This appears to be a duplicate of #41
