### ISSUE TITLE
An unexpected error occurred while searching for your Sonos System

### ISSUE THREAD

**Issue by edwardvdv** [sonos-web/sonos-web#56]
CentOS 8, inside same network as two Sonos play:1 speakers.

Output of `sonos-cli list-devices` is correct, I can see my 2 play:1 speakers with all attributes.

However, on launch of the Web UI, within 10 seconds I see:
```
An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'forEach' of undefined\n at SonosNetwork._getQueue (/root/.sonos-web/src/sonos/SonosNetwork.js:715:19)
at runMicrotasks (<anonymous>)\n
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async SonosNetwork._getAVTransportInfo (/root/.sonos-web/src/sonos/SonosNetwork.js:810:19)
at async /root/.sonos-web/src/sonos/SonosNetwork.js:624:33
at async Promise.all (index 0)
at async /root/.sonos-web/src/sonos/SonosNetwork.js:623:9","message":"Cannot read property 'forEach' of undefined"}
```

The Sonos speakers are up to date.

Any help appreciated!

**Comment by Franqqq** [comment]
I think this is the same issue.
https://github.com/Villarrealized/sonos-web/issues/41 ?

**Comment by edwardvdv** [comment]
Thanks @Franqqq you're right. I can confirm this relates to a empty play queue as well (using TuneIn here). Closing this.
