### ISSUE TITLE
Sonos Web broken 

### ISSUE THREAD

**Issue by manamandem** [sonos-web/sonos-web#63]
![image](https://user-images.githubusercontent.com/53195931/100521192-fda2e300-3199-11eb-87e6-68c81a9d076c.jpg)

**Comment by manamandem** [comment]
I have a Sonos One Gen 2

**Comment by entwistlej** [comment]
Hi, I am getting the same problem.

**Comment by NyquistFX** [comment]
Same problem!

It was working prior to system firmware upgrade.. I am currently on version 11.2 of the S1 Sonos firmware for Sonos Connect:AMP and Connect devices (I think one is actually a ZP90).

I'm sure it was OK at version 11.0, and possibly 11.1, but from 11.2 onward it appears broken. I know Sonos did change a lot of the available web pages from the devices around that time. They are also adamant they don't support firmware downgrades unfortunately.

If it's even possible to fix this with the new firmware that would be awesome.

At the time of writing they are pushing yet another update for legacy products, unfortunately it's almost necessary to do these so the device controller app's on phone/PC/etc continue to work.

**Comment by FeatheredPigeon** [comment]
I am receiving a similar error as well. I am on 11.2.4 of the S1 firmware.

**Comment by manamandem** [comment]
Is the dev going to advise or try to help or not?

**Comment by akshun-j** [comment]
version 0.94 of this app is still working.  Most recent versions are failing with above error.

**Comment by mef18** [comment]
Same problem for me. Could you help me how to install/downgrade to 0.94 version?

**Comment by mattguide** [comment]
I think this is related to #41, trying to work through it myself as of 0.99.
