### ISSUE TITLE
Top results throws "500: Cannot read property 'length' of undefined" error when when search criteria for any item (ie Album, Track etc) 

### ISSUE THREAD

**Issue by ghost** [sonos-web/sonos-web#71]
Hello,

Just installed Sonos Web yesterday and it provides excellent functionality. However I did notice an issue with the search functionality.
When carrying out a search, if any of the subcategories (ie Artsits, Albums, Songs, Generes or Playlists) do not contain the search term an error:
500: Cannot read property 'length' of undefined
will show.
Ideally all categories that have results should be shown and any category that does not bring back a result would ideally show a "No results" (or something similar) message

Also when search on the individual tabs ie and the search criteria cannot be met there are a mix of messages ie:
404: Item Not Found
or
500: Cannot read property 'map' of undefined
ideally this would result in a "No results" (or something similar) message as well.

Thanks for all your work on this.

**Comment by stufisher** [comment]
Maybe fixed in https://github.com/sonos-web/sonos-web/commit/71db5284d441f8ae1b3a2c030e1f5631174a3f33 ?
