### ISSUE TITLE
An unexpected error occurred while searching for your Sonos System

### ISSUE THREAD

**Issue by Trikos** [sonos-web/sonos-web#74]
The program cant run correctly.
Node v14.16.0
Npm v6.14.11
Win 10
![image](https://user-images.githubusercontent.com/19153649/111462802-24702f80-871f-11eb-9991-c8ebfd4bd6c5.png)
I got this error:
An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'forEach' of undefined\n at SonosNetwork._getQueue (C:\\Users\\sk8te\\.sonos-web\\src\\sonos\\SonosNetwork.js:715:19)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async SonosNetwork._getAVTransportInfo (C:\\Users\\sk8te\\.sonos-web\\src\\sonos\\SonosNetwork.js:810:19)\n at async C:\\Users\\sk8te\\.sonos-web\\src\\sonos\\SonosNetwork.js:624:33\n at async Promise.all (index 0)\n at async C:\\Users\\sk8te\\.sonos-web\\src\\sonos\\SonosNetwork.js:623:9","message":"Cannot read property 'forEach' of undefined"}

**Comment by jellmers** [comment]
I am getting the same issue, installed on my MacOS.  I have tried as User and Root and neither work...  Node-sonos is working with sonos-cli....
