### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by HIGHWOOD** [sonos-web/sonos-web#79]
I installed Sonos Web according to the read.me description. After installing I get a "Success" message, with the URL's to open Sonos Web. But when I try to open http://localhost:5050 I get an error message:

_`An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'forEach' of undefined\n at SonosNetwork._getQueue (C:\\Users\\marce\\.sonos-web\\src\\sonos\\SonosNetwork.js:715:19)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async SonosNetwork._getAVTransportInfo (C:\\Users\\marce\\.sonos-web\\src\\sonos\\SonosNetwork.js:810:19)\n at async C:\\Users\\marce\\.sonos-web\\src\\sonos\\SonosNetwork.js:624:33\n at async Promise.all (index 0)\n at async C:\\Users\\marce\\.sonos-web\\src\\sonos\\SonosNetwork.js:623:9","message":"Cannot read property 'forEach' of undefined"}`_

When I try to stop the server (sonos-web stop) a message says that the server isn't running. When I try to start the server again it shows met the Success message again.

Please can you help me? Thank you!

**Comment by mattguide** [comment]
I am running into the same problem (sorry, I'm spamming this board).  I think it's the same as #41, and there is a merge request that will solve it.  
I am trying to add the line of code on my own in the `src/sonos/SonosNetwork.js` file, but I get the same `server isn't running` message when I `sonos-web stop`. So, I am stuck.
