### ISSUE TITLE
Layout horribly broken

### ISSUE THREAD

**Issue by Villarrealized** [sonos-web/sonos-web#8]
I was working on v0.9.0 today and while I was updating the README, the layout all of a sudden became completely broken. I checked out several previous versions back as far as v0.6.0. but it's still broken. The only thing I can think of is that one of the client side dependencies was updated and is now breaking everything.

![screen shot 2019-02-18 at 4 45 20 pm](https://user-images.githubusercontent.com/5977736/52981376-a5239c80-339c-11e9-8cc7-723db7f150b6.png)

**Comment by zonurben** [comment]
It's the same with me, too. If I also start the website, the volume in all rooms is set to 0.

**Comment by Villarrealized** [comment]
Hmm, have not experienced any issue with the volume.

I have tried removing all `^` from package names to see if that would fix an issue with a package. No change. 

Below is the modified package.json I tried to use. It's obviously something with the compiler at some level...but there are no errors in the console to debug. Makes this tough to try to track down...

```javascript

{
  "name": "sonos-web",
  "version": "0.9.1",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "test:unit": "vue-cli-service test:unit"
  },
  "dependencies": {
    "axios": "0.18.0",
    "deepmerge": "3.0.0",
    "js-base64": "2.5.0",
    "material-design-icons-iconfont": "3.0.3",
    "roboto-fontface": "0.10.0",
    "socket.io-client": "2.2.0",
    "vue": "2.5.17",
    "vue-headful": "2.0.1",
    "vue-lazyload": "1.2.6",
    "vue-router": "3.0.1",
    "vuedraggable": "2.17.0",
    "vuetify": "1.3.0",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "3.3.0",
    "@vue/cli-plugin-eslint": "3.1.1",
    "@vue/cli-plugin-unit-mocha": "3.1.1",
    "@vue/cli-service": "3.4.0",
    "@vue/eslint-config-airbnb": "4.0.0",
    "@vue/test-utils": "1.0.0-beta.20",
    "babel-eslint": "10.0.1",
    "chai": "4.1.2",
    "eslint": "5.8.0",
    "eslint-plugin-vue": "5.2.2",
    "stylus": "0.54.5",
    "stylus-loader": "3.0.2",
    "vue-cli-plugin-vuetify": "0.4.6",
    "vue-template-compiler": "2.5.17",
    "vuetify-loader": "1.0.5"
  }
}

```

**Comment by Villarrealized** [comment]
Good news. Doesn't look like it's a dependency issue. Looks like there was some bug introduced in v0.9.0 that is not present in v0.8.0. Checking out the version from my existing repo did not work, but cloning and checking out v0.8.0 and the app works again... Will be looking into the commits for v0.9.0 to determine the issue.

**Comment by Villarrealized** [comment]
Seems like the issue would be a configuration issue of some kind, not a source code issue...But reviewing the commits so far doesn't give many clues.

I remember the exact moment when the issue happened, but it seems coincidental...I changed the preferences for my AdBlock extension in Chrome to exclude blocking ads on localhost:5050 and as soon as I did that, the page reloaded and the layout was broken. I can't imagine it would have an impact on the code or configuration of the project.

Still digging.

**Comment by Villarrealized** [comment]
Found the issue!

Apparently, my attempt to use css modules in `vue.config.js` completely broke the layout. Not sure why, but decided to remove it as it wasn't necessary. Thought I had already tried reverting that change and that it did nothing. But tried again, and it fixed it. Yay!

v0.9.2 fixes this issue.

**Comment by zonurben** [comment]
Good morning
The layout is now actually in order. But the control doesn't work for me. 
If I start my website xxx.xxx.xxx.xxx:5050 the window appears, the volume of the grouped Sonos speakers is set to 0. This cannot be changed. 
I suspect that a competing service on another Raspberry Pi might cause a conflict (https://github.com/jishi/node-sonos-http-api)?
I'll try this one out.

**Comment by Villarrealized** [comment]
Hmm. If you could open a separate issue and post a screenshot of what you're experiencing that would be helpful!
