### ISSUE TITLE
Searches for Sonos System forever

### ISSUE THREAD

**Issue by sixtemesseven** [sonos-web/sonos-web#80]
I have installed sonos web as described on a win10 machine, it says localhost.local:5050 is up and it does start. But it fails to discover my Sonos devices.

I have the machine running sonos web on the same network and I have disabled the win firewall completley. Still no luck. 
How would I check whats gone wrong?

**Comment by sixtemesseven** [comment]
Update: I actually got a error message in the browser now:

An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'forEach' of undefined\n at SonosNetwork._getQueue (C:\\Users\\sandbox\\.sonos-web\\src\\sonos\\SonosNetwork.js:715:19)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async SonosNetwork._getAVTransportInfo (C:\\Users\\sandbox\\.sonos-web\\src\\sonos\\SonosNetwork.js:810:19)\n at async C:\\Users\\sandbox\\.sonos-web\\src\\sonos\\SonosNetwork.js:624:33\n at async Promise.all (index 3)\n at async C:\\Users\\sandbox\\.sonos-web\\src\\sonos\\SonosNetwork.js:623:9","message":"Cannot read property 'forEach' of undefined"}

**Comment by sixtemesseven** [comment]
I also installed the sonos s1 controller on the system. It finds everything without problems.

Stupid question, does the sonos web only work with s2?

**Comment by parduhn** [comment]
Here the same thing. S1 controller and Searching for Sonos for ever. However, I do not have an browser error.

**Comment by mattguide** [comment]
I am also grappling with this error. I think this error is the same as #41. It looks like there is a merge request for it, just needs to be added.
