### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by timothee-durand** [sonos-web/sonos-web#88]
Hello,
I'm on Window 10 and I try to install the app by the cli, the cli is correctly installed but when I try to install the app by making `sonos-web install` I have this output in my console : 
```
Installing Sonos Web
√ downloading installation files
× installing front-end dependencies
error installation failed...check C:\Users\timot/.sonos-web/install.log for more details
```
and nothing in the log file...

The uninstall command works properly by the way. 

Thanks for your project and your time !

**Comment by garethhumphriesgkc** [comment]
+1.
```
/ # sonos-web install
Installing Sonos Web
✔ downloading installation files
✖ installing front-end dependencies
error installation failed...check /root/.sonos-web/install.log for more details
/ # cat /root/.sonos-web/install.log
/ # 
```

**Comment by stufisher** [comment]
Dependencies are now node 16 compatible, but npm package is not yet updated, for now you'll need to manually install.
