### ISSUE TITLE
Sometimes My Playing/Rooms don't appear

### ISSUE THREAD

**Issue by mrgrieves4** [sonos-web/sonos-web#9]
Just trying this for the first time, running on OSX Mojave.

The first time it worked great (in Firefox).  It came up quickly to show what was playing and where, and clicking around it all seemed good.

I tried it in Vivaldi, and the Now Playing artwork was missing, and it looked like nothing was playing.  I then found out if I refresh Vivaldi, or go back to Firefox and refresh there that I get one of three things:

1. It all works fine.
2. It doesn't seem to recognised what's playing.  The rooms menu is empty.  However, music library appears fine as does My Sonos.
3. Nothing appears at all, other than the menu.  Again in this state, Music Library and My Sonos work OK.

Seems random which one happens.  It probably fails more often than it works for me.

In the Console I see things like this:

TypeError: "o.track is undefined"
    albumArtURLForGroup store.js:65 albumArtURL NowPlayingBar.vue:295 get3VueJS
p NowPlayingBar.vue:1 _render19VueJS
    a es6.promise.js:75 L es6.promise.js:92 u _microtask.js:18 
vue.runtime.esm.js:1878
    ie22VueJS
a es6.promise.js:75 L es6.promise.js:92 u 

I wonder if it's some sort of race condition as it seems completely random.  I've not really got enough time to dig into it too deeply though.

it looks great when it works though.

I should say I didn't quite install it as per instructions because I didn't want to install the cli globally. So I cloned the CLI and just ran "node index install".  My mac and the Sonos are all connected to the same wifi network.  (I'm not using Sonosnet or whatever it's called, all my Sonos devices are wireless.)

**Comment by Villarrealized** [comment]
Thank you for trying it out. I am also developing and testing on macOS Mojave. Looking at the code, I see where the error seems to be happening although I have never experienced it. The track data appears to not exist, which is why you aren't getting any track information.

```javascript
if (group) {
  // track is undefined apparently
  return group.track.albumArtURL
  || (group.tvPlaying ? state.tvAlbumArtURL : state.defaultAlbumArtURL);
}
return state.defaultAlbumArtURL;
```

I can change it to this, although that will only help with providing a default album art image. I'll have to try to see if there is any reason why the track data wouldn't be there in the first place.
```javascript
if (group && group.track) {
  return group.track.albumArtURL
  || (group.tvPlaying ? state.tvAlbumArtURL : state.defaultAlbumArtURL);
}
return state.defaultAlbumArtURL;
```

**Comment by Villarrealized** [comment]
The changes I suggested in my previous comment were added to v0.9.4. I'm going to close this issue for now. Feel free to reopen if it's still an issue after updating.
