### ISSUE TITLE
Error: "An unexpected error occurred while searching for your Sonos System: 

### ISSUE THREAD

**Issue by bdog1** [sonos-web/sonos-web#92]
Windows 10 
Installed latest version of NPM and Node
NPM version 6.14.13
Node Version 14.17.3

Installed necessary packages for Sonos Web. 
Looked like a good install.

Launched a local browser and pointed to http://localhost:5050
Received the following error

"An unexpected error occurred while searching for your Sonos System: {"stack":"TypeError: Cannot read property 'forEach' of undefined\n at SonosNetwork._getQueue (C:\\Users\\BDOG\\.sonos-web\\src\\sonos\\SonosNetwork.js:715:19)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at async SonosNetwork._getAVTransportInfo (C:\\Users\\BDOG\\.sonos-web\\src\\sonos\\SonosNetwork.js:810:19)\n at async C:\\Users\\BDOG\\.sonos-web\\src\\sonos\\SonosNetwork.js:624:33\n at async Promise.all (index 0)\n at async C:\\Users\\BDOG\\.sonos-web\\src\\sonos\\SonosNetwork.js:623:9","message":"Cannot read property 'forEach' of undefined"} "

Attempted using my actual IP address on the local network
http://192.168.1.21:5050
Received the same error as above.

**Comment by bdog1** [comment]
Perhaps its a firewall issue? Just spitballing here.

**Comment by IngoK1** [comment]
Same problem here - in my case I am already on Sonos S2, maybe that is the problem...
