### ISSUE TITLE
Abandonned project ?

### ISSUE THREAD

**Issue by JamesDAdams** [sonos-web/sonos-web#99]
The project are abandoned ?

**Comment by sysadmin0815** [comment]
looks like it is not maintained anymore... sad.

**Comment by JamesDAdams** [comment]
yes :(

**Comment by timsntech** [comment]
just found my way here, too bad that its unmaintained, looks like a very cool project.

**Comment by atlienk** [comment]
Was just thinking the same thing! Bummer.

**Comment by Villarrealized** [comment]
@stufisher has been working on the project, fixing some bugs, and adding a few new features. I have transferred ownership to the `sonos-web` organization. Stu and myself are owners. I suspect he will be contributing more to the project. Unfortunately, I haven't had much time to devote to this, so I'm thankful for the contributions Stu has made to hopefully breathe some new life into this!

**Comment by atlienk** [comment]
Thanks for taking ownership! I'll check out the new release shortly.
